version: '3'
services:
    config-loader:
        labels:
            app: config-loader
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            XDEBUG_MODE: 'debug,coverage'
            PHP_IDE_CONFIG: 'serverName=app'
        networks:
        - "config_loader_network"

networks:
    config_loader_network:
        driver: bridge
