version: '3'
services:
    config-loader:
        labels:
            app: config-loader
        build:
            context: ../
            dockerfile: docker/Dockerfile
        networks:
        - "default"

networks:
    default:
        driver: bridge
